### ISSUE TITLE
Load Weights in demo.py going wrong - YOLOV3 OBJECT DETECTION

### ISSUE THREAD

**Issue by fnando1995** [YunYang1994/TensorFlow2.0-Examples#35]
Hello,

while testing for frist time. I downloaded the yolo weights and try the image_demo.py. but at load_weights() in conv_layer_name = conv2d_9

model.Summary():
`conv2d_9 (Conv2D)               (None, 52, 52, 256)  294912      zero_padding2d_2[0][0]`

traceback
```
Traceback (most recent call last):
  File "image_demo.py", line 41, in <module>
    utils.load_weights(model, "./yolov3.weights")
  File "/PATH/TensorFlow2.0-Examples/4-Object_Detection/YOLOV3/core/utils.py", line 51, in load_weights
    conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 95566 into shape (256,128,3,3)
```
Any clue of what is going on? i dont really want to change the load_weights func.

kind regards

**Comment by fnando1995** [comment]
Nevermind. Only weights file corrupted.
