### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError:  RPN train.py

### ISSUE THREAD

**Issue by snow-wind-001** [YunYang1994/TensorFlow2.0-Examples#49]
Traceback (most recent call last):
  File "/home/z840/PycharmProjects/TensorFlow2.0-Examples/4-Object_Detection/RPN/train.py", line 136, in <module>
    score_loss, boxes_loss = compute_loss(target_scores, target_bboxes, target_masks, pred_scores, pred_bboxes)
  File "/home/z840/PycharmProjects/TensorFlow2.0-Examples/4-Object_Detection/RPN/train.py", line 110, in compute_loss
    boxes_loss = 0.5 * tf.pow(boxes_loss, 2) * tf.cast(boxes_loss<1, tf.float32) + (boxes_loss - 0.5) * tf.cast(boxes_loss >=1, tf.float32)
  File "/home/z840/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 884, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/z840/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1180, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "/home/z840/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 6487, in mul
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute Mul as input #1(zero-based) was expected to be a double tensor but is a float tensor [Op:Mul] name: mul/

在训练时出现了这个错误，麻烦大神看一下

**Comment by snow-wind-001** [comment]
> Traceback (most recent call last):
> File "/home/z840/PycharmProjects/TensorFlow2.0-Examples/4-Object_Detection/RPN/train.py", line 136, in
> score_loss, boxes_loss = compute_loss(target_scores, target_bboxes, target_masks, pred_scores, pred_bboxes)
> File "/home/z840/PycharmProjects/TensorFlow2.0-Examples/4-Object_Detection/RPN/train.py", line 110, in compute_loss
> boxes_loss = 0.5 * tf.pow(boxes_loss, 2) * tf.cast(boxes_loss<1, tf.float32) + (boxes_loss - 0.5) * tf.cast(boxes_loss >=1, tf.float32)
> File "/home/z840/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 884, in binary_op_wrapper
> return func(x, y, name=name)
> File "/home/z840/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1180, in _mul_dispatch
> return gen_math_ops.mul(x, y, name=name)
> File "/home/z840/anaconda3/envs/tf2.0/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 6487, in mul
> _six.raise_from(_core._status_to_exception(e.code, message), None)
> File "", line 3, in raise_from
> tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute Mul as input #1(zero-based) was expected to be a double tensor but is a float tensor [Op:Mul] name: mul/

在训练时出现了这个错误，如果有时间,麻烦博主看一下

**Comment by snow-wind-001** [comment]
解决了这个问题，将一下代码转化tf.float32
boxes_loss = 0.5 * tf.cast(tf.pow(boxes_loss, 2),tf.float32) * tf.cast(boxes_loss<1, tf.float32) + tf.cast((boxes_loss - 0.5),tf.float32) * tf.cast(boxes_loss >=1, tf.float32)

total_loss =tf.cast(score_loss,tf.float32)  + tf.cast(lambda_scale * boxes_loss,tf.float32)
