### ISSUE TITLE
执行$ python yymnist/make_data.py --images_num 1000 --images_path ./data/dataset/train --labels_txt ./data/dataset/yymnist_ train.txt

### ISSUE THREAD

**Issue by yingluojiuchan** [YunYang1994/TensorFlow2.0-Examples#79]
出现
Traceback (most recent call last):
  File "yymnist/make_data.py", line 114, in <module>
    data[0] = make_image(data, image_paths[idx], ratio)
  File "yymnist/make_data.py", line 62, in make_image
    image = cv2.resize(image, (int(28*ratio), int(28*ratio)))
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

**Comment by angwangiot** [comment]
出现了同样的错误

**Comment by angwangiot** [comment]
我又用了自己的训练集测试可以了，不用yymnist。

**Comment by liyuxuan89** [comment]
When reading a image with imread, if the path doesn't exist, it will return a None without raising an error. A None object can't be resized, thus having an assertion failure. You may want to check the path of your training data.

**Comment by ShirleyHe2020** [comment]
> 我又用了自己的训练集测试可以了，不用yymnist。

>我用自己的训练集发现报错如下： 
Traceback (most recent call last):
  File "make_data.py", line 111, in <module>
    data[0] = make_image(data, image_paths[idx], ratio)
IndexError: list index out of range
