### ISSUE TITLE
请教 FCN训练时出错 

### ISSUE THREAD

**Issue by huihua7882** [YunYang1994/TensorFlow2.0-Examples#93]
Epoch 1/30
Traceback (most recent call last):
  File "/home/hua/PycharmProjects/test/5ImageSegmentation/1FCN/train.py", line 28, in <module>
    model.fit_generator(TrainSet, steps_per_epoch=6000, epochs=30, callbacks=[callback])
  File "/home/hua/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/hua/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1479, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/hua/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/hua/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 848, in fit
    tmp_logs = train_function(iterator)
  File "/home/hua/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/home/hua/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 627, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/hua/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 506, in _initialize
    *args, **kwds))
  File "/home/hua/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2446, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/hua/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/hua/.local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/hua/.local/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/hua/.local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/hua/.local/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    /home/hua/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py:571 train_function  *
        outputs = self.distribute_strategy.run(
    /home/hua/PycharmProjects/test/5ImageSegmentation/1FCN/fcn8s.py:106 call  *
        h = h[:, 5:5 + upscore2.shape[1], 5:5 + upscore2.shape[2], :]  # channel last

    TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

Process finished with exit code 1

**Comment by huihua7882** [comment]
我知道了 parser_voc.py 里的 misc.imread()接口过时，我换接口导致生成的txt数据不对导致. 大神的代码结构简单 最适合学习用 非常感谢分享.

**Comment by taolon2018** [comment]
@huihua7882  would you mind share how you resolved it? I had the same problem, still couldn't train the model even though I downgraded scipy to 1.10.

**Comment by UJoeNK** [comment]
请教一下这个问题最后具体是咋解决的呢 @huihua7882
